name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform

  validate-python:
    name: Validate Python Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check syntax
        run: |
          python -m py_compile services/producer/app.py
          python -m py_compile services/consumer_short/app.py
          python -m py_compile services/consumer_long/app.py
